# Generated by Django 3.2.13 on 2023-01-08 20:43

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order_id', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=200, null=True)),
                ('card_name', models.CharField(blank=True, max_length=200, null=True)),
                ('order_status', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_ref_no', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payuid', models.CharField(blank=True, max_length=200, null=True)),
                ('mihpayuid', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('payment_channel', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_datetime', models.CharField(blank=True, max_length=200, null=True)),
                ('response_code', models.CharField(blank=True, max_length=200, null=True)),
                ('response_message', models.CharField(blank=True, max_length=200, null=True)),
                ('error_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('cardmasked', models.CharField(blank=True, max_length=200, null=True)),
                ('failure_message', models.TextField(blank=True, max_length=200, null=True)),
                ('status_message', models.TextField(blank=True, max_length=200, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_payment_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_payment_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
                'db_table': 'payment',
            },
        ),
    ]
